// All user-facing text in the app lives here — including error messages,
// toast message prefixes, and accessibility labels, not just visible
// labels. Edit strings directly in this file (in the GitHub repo, or
// locally) to change wording anywhere in the app without touching
// component logic. Anything with {placeholders} like {name} is filled in
// with real data at runtime — keep those tokens intact, just reword the
// surrounding text.
//
// The one deliberate exception: public/manifest.json (the PWA name and
// description) can't reference this file at all, since it's a static file
// the browser reads directly before any of this app's code runs. Once this
// app is packaged for the App Store, a few more strings will live outside
// this file for the same reason — permission usage descriptions and the
// App Store listing itself are read by iOS/App Store Connect, not by this
// codebase.

export const copy = {
  common: {
    appName: "Houselights",
    settingsLabel: "Settings",
    closeLabel: "Close",
    earnedPrefix: "Earned",
    removedPrefix: "Removed",
    imageReadError: "Couldn't read that image",
    imageShrinkError: "Couldn't shrink that image enough for a Spotify cover.",
    canvasNotSupportedError: "Canvas not supported",
    setlistNotConfiguredError: "Setlist data isn't set up yet — add a SETLISTFM_API_KEY to enable it.",
    missingSpotifyIdError: "This artist is missing its Spotify ID — try removing and re-adding them.",
  },

  home: {
    tagline: "Create better playlists.",
    ctaConnect: "Connect Spotify",
    ctaGuest: "Continue as Guest",
    ctaGuestNote: "Search and build a lineup now — connect later to save it to Spotify.",
  },

  lineup: {
    title: "Who's playing?",
    searchPlaceholder: "Search artists on Spotify",
    eventDateLabel: "Event date",
    eventDateOptional: "(optional)",

    playlistSizeLabel: "Playlist size",
    sizeModeSongs: "Songs",
    sizeModeTime: "Time",
    totalSongsLabel: "Total songs",
    totalTimeLabel: "Total length",
    timePreset30: "30 min",
    timePreset60: "1 hr",
    timePreset90: "1.5 hr",
    timePreset120: "2 hr",
    timePreset180: "3 hr",

    posterUploadIdle: "Upload a poster to auto-add artists",
    posterUploadLoading: "Reading poster...",
    posterFoundHeading: "Found on your poster",
    posterNoMatch: "No Spotify match found",
    posterCancel: "Cancel",
    posterAddOne: "Add",
    posterAddMany: "artists",
    posterNotConfigured: "Poster reading isn't set up yet — add an ANTHROPIC_API_KEY to enable it.",
    posterReadError: "Couldn't read that poster.",
    posterNoNamesFound: "Couldn't find any artist names on that image. Try a clearer photo.",
    posterImageReadError: "Couldn't read that image.",
    decreaseLabel: "Decrease",
    increaseLabel: "Increase",

    connectPrompt: "Connect Spotify to search for artists.",
    connectButton: "Connect Spotify",
    searching: "Searching...",
    searchFailedPrefix: "Search failed",
    noResults: "No artists found — try a different spelling or search.",
    setlistFilterFailedPrefix: "Setlist filter couldn't load for",
    setlistFilterWorkedPrefix: "Using recent setlists for",
    artistFallbackGenre: "Artist",
    seenPrefix: "You've seen them",
    editingBanner: "Editing an existing playlist — Create will save changes to it instead of making a new one.",
    cancelEdit: "Cancel edit",
    guestBanner: "Browsing as a guest — connect Spotify to save this playlist.",
    guestBannerAction: "Connect",
    timeSuffix: "time",
    timesSuffix: "times",
    lastPlayedPrefix: "Last played",
    setlistChecking: "Checking for a recent setlist...",
    setlistFound: "Setlist found",
    setlistErrorPrefix: "Setlist lookup failed:",
    setlistNotFound: "No recent setlist found — using popular songs instead.",
    songsSuffix: "songs",

    lineupLabel: "Your lineup",
    dragHint: "Drag to reorder — whoever's on top is the headliner.",
    clearAll: "Clear all",
    emptyLineup: "Search for an artist above to get started.",
    headlinerTag: "Headliner",

    weightLabel: "Share",
    weightGoalSuffix: "goal",
    addSpecificSongs: "Add specific songs",
    pickedSongsLabel: "Picked songs",
    remove: "Remove",
    searchSongPlaceholder: "Search a song title",
    add: "Add",

    ctaPreview: "Preview playlist",
    shortfallDisclaimer: "A complete song list isn't always possible — some artists may come up short depending on what's available.",
    generatingPhrases: [
      "Checking the setlist...",
      "Finding the openers...",
      "Warming up...",
      "Counting songs...",
    ],
  },

  preview: {
    title: "How's this look?",
    emptyState: "Your lineup didn't return any tracks. Go back and adjust your filters or song counts.",
    previewHintPrefix: "Tap",
    previewHintSuffix: "next to a track to listen on Spotify before you commit to it.",
    viewArtists: "Artists",
    viewSongs: "Songs",
    flipOrder: "Flip order",
    shuffle: "Shuffle",
    addSong: "Add a song",
    searchSongPlaceholder: "Search a song title",
    add: "Add",
    createButton: "Create playlist",
    continueToSave: "Continue to save changes",
    saveAsDraft: "Save as draft",
    loginToCreate: "Connect Spotify to create",
  },

  create: {
    title: "New playlist",
    editTitle: "Edit playlist",
    saveChanges: "Save changes",
    coverImageError: "Couldn't use that image — try a different one.",
    saveAsNew: "Save as a new playlist instead",
    addCover: "Add cover",
    changeCover: "Change cover",
    coverHint: "JPEG or PNG",
    coverModalTitle: "Cover",
    uploadTab: "Upload photo",
    generateTab: "Generate cover",
    uploadPrompt: "Tap to choose a photo",
    uploadCoverButton: "Upload",
    replaceCoverButton: "Replace",
    deleteCoverButton: "Delete",
    backgroundLabel: "Background",
    generatePreviewNote: "Preview updates as you change background and artists.",
    artistsToIncludeLabel: "Artists to include",
    artistsToIncludeNote: "Up to 4 — pick one for it to appear twice, or several to line them up.",
    useThisCover: "Use this cover",
    playlistNameLabel: "Playlist name",
    descriptionLabel: "Description",
    doneButton: "Done",
    creatingPhrases: ["Packing the setlist...", "Sending it to Spotify...", "Almost there..."],
  },

  success: {
    title: "Added to Spotify",
    firstTitle: "Your first show, prepped 🎉",
    updatedTitle: "Changes saved",
    firstSuffix: "welcome to Houselights",
    coverFailed: "Playlist's live, but the cover image didn't attach — you can add one later from Spotify.",
    openInSpotify: "Open in Spotify",
    buildAnother: "Build another",
    viewPlaylists: "View playlists",
    fallbackName: "Your playlist",
  },

  playlists: {
    title: "Playlists",
    subtitleEmpty: "Playlists you've already sent to Spotify",
    encoreButton: "Stats",
    emptyMessage: "Nothing here yet — build your first lineup and it'll show up once it's live on Spotify.",
    buildLineupLink: "Build your lineup",
    resumeDraft: "Resume",
    draftsLabel: "Drafts",
    draftsNote: "Built as a guest, not yet sent to Spotify — connect and resume to finish one.",
    draftSavedToast: "Saved to Drafts",
    open: "Spotify",
    copyLink: "Copy link",
    linkCopied: "Copied!",
    edit: "Edit",
    deleteAction: "Delete",
    previewError: "Couldn't load that playlist. Try again.",
    previewErrorScope: "This needs a fresh Spotify connection to read playlists you've already created.",
    reconnect: "Reconnect",
    previousEventsLabel: "Previous events",
    previousEventsEmpty: "No past shows yet.",
  },

  settings: {
    title: "Settings",
    accountLabel: "Account",
    checking: "Checking...",
    connected: "Connected to Spotify",
    notConnected: "Not connected",
    connectedNote: "Your session is active on this device.",
    notConnectedNote: "Connect from the home screen to build a lineup.",
    switchAccount: "Switch account",
    connectButton: "Connect Spotify",
    logout: "Log out",
    switchNote:
      "Switching account sends you back through Spotify's login screen, so you can sign in with a different account if you have more than one.",
    colorblindLabel: "Colour vision",
    colorblindNote: "Changes artist and Wristband colours across the app to be easier to tell apart.",
    colorblindOff: "Default",
    colorblindOffNote: "The app's standard colours.",
    colorblindRedGreen: "Red-green",
    colorblindRedGreenNote: "For protanopia and deuteranopia, the most common types.",
    colorblindBlueYellow: "Blue-yellow",
    colorblindBlueYellowNote: "For tritanopia, a rarer type.",
    appearanceLabel: "Appearance",
    lightsUp: "Lights up",
    lightsDown: "Lights down",
    appearanceNote: "Switches between light and dark mode.",
    backupLabel: "Backup",
    backupNote: "Everything lives only on this device — export a backup to keep it safe, or bring it to a new phone.",
    exportButton: "Export a backup",
    importButton: "Import a backup",
    exportDone: "Backup saved.",
    importInvalidFile: "That doesn't look like a Houselights backup file.",
    importConfirmPrompt: "This replaces everything currently saved on this device with the backup",
    importConfirmButton: "Yes, restore",
    importingMessage: "Restoring…",
    dangerLabel: "Danger zone",
    deleteAllTitle: "Delete all playlists",
    deleteAllNote: "Clears your Playlists history in Houselights. Doesn't touch anything already on Spotify.",
    deleteAllButton: "Delete",
    clearProgressTitle: "Clear progress",
    clearProgressNote: "Deletes your Playlists history and re-locks every Wristband.",
    clearProgressButton: "Clear",
    confirmPrompt: "Delete every playlist from this list? This can't be undone.",
    confirmPromptProgress: "Clear all playlists and re-lock every Wristband? This can't be undone.",
    cancel: "Cancel",
    confirmDelete: "Yes, delete",
    deletedConfirmation: "All playlists deleted.",
    clearedConfirmation: "Progress cleared — every Wristband is locked again.",
    patchNotesLabel: "Patch notes",
    currentVersionPrefix: "Current version",
  },

  nextUp: {
    title: "Next Up",
    subtitleEmpty: "Nothing on the horizon yet",
    subtitleSuffix: "on the horizon",
    emptyMessage: "No dated shows coming up — add a date next time you build a lineup and it'll show up here.",
    buildLineupLink: "Build your lineup",
  },

  nav: {
    newEvent: "New event",
    playlists: "Playlists",
    wristbands: "Wristbands",
  },

  wristbands: {
    title: "Wristbands",
    unlockedToastLabel: "Wristband unlocked",
    viewAction: "View",
  },

  encore: {
    title: "Stats",
    subtitle: "A look back at everything you've built",
    emptyMessage: "Nothing to look back on yet — build your first lineup and it'll show up here.",
    showsPrepped: "Shows prepped",
    showsAttended: "Shows attended",
    songsQueued: "Songs queued",
    timeQueued: "Time queued",
    topArtistLabel: "Most-featured headliner",
    longestLabel: "Longest playlist",
    firstLabel: "Your first lineup",
    tracksSuffix: "tracks",
    timeSuffix: "time",
    timesSuffix: "times",
  },

  filters: {
    popular: "Most popular",
    setlist: "Setlist",
  },
};
